# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_BC', [dirname(__file__)])
        except ImportError:
            import _BC
            return _BC
        if fp is not None:
            try:
                _mod = imp.load_module('_BC', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _BC = swig_import_helper()
    del swig_import_helper
else:
    import _BC
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _BC.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _BC.SwigPyIterator_value(self)
    def incr(self, n=1): return _BC.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _BC.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _BC.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _BC.SwigPyIterator_equal(self, *args)
    def copy(self): return _BC.SwigPyIterator_copy(self)
    def next(self): return _BC.SwigPyIterator_next(self)
    def __next__(self): return _BC.SwigPyIterator___next__(self)
    def previous(self): return _BC.SwigPyIterator_previous(self)
    def advance(self, *args): return _BC.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _BC.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _BC.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _BC.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _BC.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _BC.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _BC.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _BC.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Mesh(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Mesh, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Mesh, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def saveToHDF5(self, *args): return _BC.Mesh_saveToHDF5(self, *args)
    def cellPolyOrder(self, *args): return _BC.Mesh_cellPolyOrder(self, *args)
    def getActiveCellIDs(self): return _BC.Mesh_getActiveCellIDs(self)
    def getDimension(self): return _BC.Mesh_getDimension(self)
    def hRefine(self, *args): return _BC.Mesh_hRefine(self, *args)
    def numActiveElements(self): return _BC.Mesh_numActiveElements(self)
    def numFluxDofs(self): return _BC.Mesh_numFluxDofs(self)
    def numFieldDofs(self): return _BC.Mesh_numFieldDofs(self)
    def numGlobalDofs(self): return _BC.Mesh_numGlobalDofs(self)
    def numElements(self): return _BC.Mesh_numElements(self)
    def pRefine(self, *args): return _BC.Mesh_pRefine(self, *args)
    def registerSolution(self, *args): return _BC.Mesh_registerSolution(self, *args)
    def vertexIndicesForCell(self, *args): return _BC.Mesh_vertexIndicesForCell(self, *args)
    def verticesForCell(self, *args): return _BC.Mesh_verticesForCell(self, *args)
    __swig_destroy__ = _BC.delete_Mesh
    __del__ = lambda self : None;
Mesh_swigregister = _BC.Mesh_swigregister
Mesh_swigregister(Mesh)

class MeshPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MeshPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MeshPtr, name)
    __repr__ = _swig_repr
    def __deref__(self): return _BC.MeshPtr___deref__(self)
    def __init__(self): 
        this = _BC.new_MeshPtr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _BC.delete_MeshPtr
    __del__ = lambda self : None;
    def saveToHDF5(self, *args): return _BC.MeshPtr_saveToHDF5(self, *args)
    def cellPolyOrder(self, *args): return _BC.MeshPtr_cellPolyOrder(self, *args)
    def getActiveCellIDs(self): return _BC.MeshPtr_getActiveCellIDs(self)
    def getDimension(self): return _BC.MeshPtr_getDimension(self)
    def hRefine(self, *args): return _BC.MeshPtr_hRefine(self, *args)
    def numActiveElements(self): return _BC.MeshPtr_numActiveElements(self)
    def numFluxDofs(self): return _BC.MeshPtr_numFluxDofs(self)
    def numFieldDofs(self): return _BC.MeshPtr_numFieldDofs(self)
    def numGlobalDofs(self): return _BC.MeshPtr_numGlobalDofs(self)
    def numElements(self): return _BC.MeshPtr_numElements(self)
    def pRefine(self, *args): return _BC.MeshPtr_pRefine(self, *args)
    def registerSolution(self, *args): return _BC.MeshPtr_registerSolution(self, *args)
    def vertexIndicesForCell(self, *args): return _BC.MeshPtr_vertexIndicesForCell(self, *args)
    def verticesForCell(self, *args): return _BC.MeshPtr_verticesForCell(self, *args)
MeshPtr_swigregister = _BC.MeshPtr_swigregister
MeshPtr_swigregister(MeshPtr)

class BC(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BC, name)
    __repr__ = _swig_repr
    def __init__(self, legacySubclass=False): 
        this = _BC.new_BC(legacySubclass)
        try: self.this.append(this)
        except: self.this = this
    def bcsImposed(self, *args): return _BC.BC_bcsImposed(self, *args)
    def singlePointBC(self, *args): return _BC.BC_singlePointBC(self, *args)
    def valueForSinglePointBC(self, *args): return _BC.BC_valueForSinglePointBC(self, *args)
    def vertexForSinglePointBC(self, *args): return _BC.BC_vertexForSinglePointBC(self, *args)
    def imposeZeroMeanConstraint(self, *args): return _BC.BC_imposeZeroMeanConstraint(self, *args)
    def addDirichlet(self, *args): return _BC.BC_addDirichlet(self, *args)
    def addSinglePointBC(self, *args): return _BC.BC_addSinglePointBC(self, *args)
    def addZeroMeanConstraint(self, *args): return _BC.BC_addZeroMeanConstraint(self, *args)
    def removeZeroMeanConstraint(self, *args): return _BC.BC_removeZeroMeanConstraint(self, *args)
    def getDirichletBC(self, *args): return _BC.BC_getDirichletBC(self, *args)
    def getSpatiallyFilteredFunctionForDirichletBC(self, *args): return _BC.BC_getSpatiallyFilteredFunctionForDirichletBC(self, *args)
    __swig_destroy__ = _BC.delete_BC
    __del__ = lambda self : None;
BC_swigregister = _BC.BC_swigregister
BC_swigregister(BC)

class BCPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BCPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BCPtr, name)
    __repr__ = _swig_repr
    def __deref__(self): return _BC.BCPtr___deref__(self)
    def __init__(self): 
        this = _BC.new_BCPtr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _BC.delete_BCPtr
    __del__ = lambda self : None;
    def bcsImposed(self, *args): return _BC.BCPtr_bcsImposed(self, *args)
    def singlePointBC(self, *args): return _BC.BCPtr_singlePointBC(self, *args)
    def valueForSinglePointBC(self, *args): return _BC.BCPtr_valueForSinglePointBC(self, *args)
    def vertexForSinglePointBC(self, *args): return _BC.BCPtr_vertexForSinglePointBC(self, *args)
    def imposeZeroMeanConstraint(self, *args): return _BC.BCPtr_imposeZeroMeanConstraint(self, *args)
    def addDirichlet(self, *args): return _BC.BCPtr_addDirichlet(self, *args)
    def addSinglePointBC(self, *args): return _BC.BCPtr_addSinglePointBC(self, *args)
    def addZeroMeanConstraint(self, *args): return _BC.BCPtr_addZeroMeanConstraint(self, *args)
    def removeZeroMeanConstraint(self, *args): return _BC.BCPtr_removeZeroMeanConstraint(self, *args)
    def getDirichletBC(self, *args): return _BC.BCPtr_getDirichletBC(self, *args)
    def getSpatiallyFilteredFunctionForDirichletBC(self, *args): return _BC.BCPtr_getSpatiallyFilteredFunctionForDirichletBC(self, *args)
BCPtr_swigregister = _BC.BCPtr_swigregister
BCPtr_swigregister(BCPtr)

# This file is compatible with both classic and new-style classes.


