# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_SpatialFilter', [dirname(__file__)])
        except ImportError:
            import _SpatialFilter
            return _SpatialFilter
        if fp is not None:
            try:
                _mod = imp.load_module('_SpatialFilter', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _SpatialFilter = swig_import_helper()
    del swig_import_helper
else:
    import _SpatialFilter
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _SpatialFilter.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _SpatialFilter.SwigPyIterator_value(self)
    def incr(self, n=1): return _SpatialFilter.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _SpatialFilter.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _SpatialFilter.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _SpatialFilter.SwigPyIterator_equal(self, *args)
    def copy(self): return _SpatialFilter.SwigPyIterator_copy(self)
    def next(self): return _SpatialFilter.SwigPyIterator_next(self)
    def __next__(self): return _SpatialFilter.SwigPyIterator___next__(self)
    def previous(self): return _SpatialFilter.SwigPyIterator_previous(self)
    def advance(self, *args): return _SpatialFilter.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _SpatialFilter.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _SpatialFilter.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _SpatialFilter.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _SpatialFilter.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _SpatialFilter.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _SpatialFilter.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _SpatialFilter.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _SpatialFilter.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _SpatialFilter.DoubleVector___nonzero__(self)
    def __bool__(self): return _SpatialFilter.DoubleVector___bool__(self)
    def __len__(self): return _SpatialFilter.DoubleVector___len__(self)
    def pop(self): return _SpatialFilter.DoubleVector_pop(self)
    def __getslice__(self, *args): return _SpatialFilter.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _SpatialFilter.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _SpatialFilter.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _SpatialFilter.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _SpatialFilter.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _SpatialFilter.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _SpatialFilter.DoubleVector_append(self, *args)
    def empty(self): return _SpatialFilter.DoubleVector_empty(self)
    def size(self): return _SpatialFilter.DoubleVector_size(self)
    def clear(self): return _SpatialFilter.DoubleVector_clear(self)
    def swap(self, *args): return _SpatialFilter.DoubleVector_swap(self, *args)
    def get_allocator(self): return _SpatialFilter.DoubleVector_get_allocator(self)
    def begin(self): return _SpatialFilter.DoubleVector_begin(self)
    def end(self): return _SpatialFilter.DoubleVector_end(self)
    def rbegin(self): return _SpatialFilter.DoubleVector_rbegin(self)
    def rend(self): return _SpatialFilter.DoubleVector_rend(self)
    def pop_back(self): return _SpatialFilter.DoubleVector_pop_back(self)
    def erase(self, *args): return _SpatialFilter.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _SpatialFilter.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _SpatialFilter.DoubleVector_push_back(self, *args)
    def front(self): return _SpatialFilter.DoubleVector_front(self)
    def back(self): return _SpatialFilter.DoubleVector_back(self)
    def assign(self, *args): return _SpatialFilter.DoubleVector_assign(self, *args)
    def resize(self, *args): return _SpatialFilter.DoubleVector_resize(self, *args)
    def insert(self, *args): return _SpatialFilter.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _SpatialFilter.DoubleVector_reserve(self, *args)
    def capacity(self): return _SpatialFilter.DoubleVector_capacity(self)
    __swig_destroy__ = _SpatialFilter.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _SpatialFilter.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class SpatialFilter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SpatialFilter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SpatialFilter, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def matchesPoint(self, *args): return _SpatialFilter.SpatialFilter_matchesPoint(self, *args)
    __swig_getmethods__["unionFilter"] = lambda x: _SpatialFilter.SpatialFilter_unionFilter
    if _newclass:unionFilter = staticmethod(_SpatialFilter.SpatialFilter_unionFilter)
    __swig_getmethods__["intersectionFilter"] = lambda x: _SpatialFilter.SpatialFilter_intersectionFilter
    if _newclass:intersectionFilter = staticmethod(_SpatialFilter.SpatialFilter_intersectionFilter)
    __swig_getmethods__["negatedFilter"] = lambda x: _SpatialFilter.SpatialFilter_negatedFilter
    if _newclass:negatedFilter = staticmethod(_SpatialFilter.SpatialFilter_negatedFilter)
    __swig_getmethods__["matchingX"] = lambda x: _SpatialFilter.SpatialFilter_matchingX
    if _newclass:matchingX = staticmethod(_SpatialFilter.SpatialFilter_matchingX)
    __swig_getmethods__["matchingY"] = lambda x: _SpatialFilter.SpatialFilter_matchingY
    if _newclass:matchingY = staticmethod(_SpatialFilter.SpatialFilter_matchingY)
    __swig_getmethods__["lessThanX"] = lambda x: _SpatialFilter.SpatialFilter_lessThanX
    if _newclass:lessThanX = staticmethod(_SpatialFilter.SpatialFilter_lessThanX)
    __swig_getmethods__["lessThanY"] = lambda x: _SpatialFilter.SpatialFilter_lessThanY
    if _newclass:lessThanY = staticmethod(_SpatialFilter.SpatialFilter_lessThanY)
    __swig_getmethods__["greaterThanX"] = lambda x: _SpatialFilter.SpatialFilter_greaterThanX
    if _newclass:greaterThanX = staticmethod(_SpatialFilter.SpatialFilter_greaterThanX)
    __swig_getmethods__["greaterThanY"] = lambda x: _SpatialFilter.SpatialFilter_greaterThanY
    if _newclass:greaterThanY = staticmethod(_SpatialFilter.SpatialFilter_greaterThanY)
    __swig_getmethods__["allSpace"] = lambda x: _SpatialFilter.SpatialFilter_allSpace
    if _newclass:allSpace = staticmethod(_SpatialFilter.SpatialFilter_allSpace)
    __swig_destroy__ = _SpatialFilter.delete_SpatialFilter
    __del__ = lambda self : None;
SpatialFilter_swigregister = _SpatialFilter.SpatialFilter_swigregister
SpatialFilter_swigregister(SpatialFilter)

def SpatialFilter_unionFilter(*args):
  return _SpatialFilter.SpatialFilter_unionFilter(*args)
SpatialFilter_unionFilter = _SpatialFilter.SpatialFilter_unionFilter

def SpatialFilter_intersectionFilter(*args):
  return _SpatialFilter.SpatialFilter_intersectionFilter(*args)
SpatialFilter_intersectionFilter = _SpatialFilter.SpatialFilter_intersectionFilter

def SpatialFilter_negatedFilter(*args):
  return _SpatialFilter.SpatialFilter_negatedFilter(*args)
SpatialFilter_negatedFilter = _SpatialFilter.SpatialFilter_negatedFilter

def SpatialFilter_matchingX(*args):
  return _SpatialFilter.SpatialFilter_matchingX(*args)
SpatialFilter_matchingX = _SpatialFilter.SpatialFilter_matchingX

def SpatialFilter_matchingY(*args):
  return _SpatialFilter.SpatialFilter_matchingY(*args)
SpatialFilter_matchingY = _SpatialFilter.SpatialFilter_matchingY

def SpatialFilter_lessThanX(*args):
  return _SpatialFilter.SpatialFilter_lessThanX(*args)
SpatialFilter_lessThanX = _SpatialFilter.SpatialFilter_lessThanX

def SpatialFilter_lessThanY(*args):
  return _SpatialFilter.SpatialFilter_lessThanY(*args)
SpatialFilter_lessThanY = _SpatialFilter.SpatialFilter_lessThanY

def SpatialFilter_greaterThanX(*args):
  return _SpatialFilter.SpatialFilter_greaterThanX(*args)
SpatialFilter_greaterThanX = _SpatialFilter.SpatialFilter_greaterThanX

def SpatialFilter_greaterThanY(*args):
  return _SpatialFilter.SpatialFilter_greaterThanY(*args)
SpatialFilter_greaterThanY = _SpatialFilter.SpatialFilter_greaterThanY

def SpatialFilter_allSpace():
  return _SpatialFilter.SpatialFilter_allSpace()
SpatialFilter_allSpace = _SpatialFilter.SpatialFilter_allSpace

class SpatialFilterPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SpatialFilterPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SpatialFilterPtr, name)
    __repr__ = _swig_repr
    def __deref__(self): return _SpatialFilter.SpatialFilterPtr___deref__(self)
    def __or__(self, *args): return _SpatialFilter.SpatialFilterPtr___or__(self, *args)
    def __and__(self, *args): return _SpatialFilter.SpatialFilterPtr___and__(self, *args)
    def __invert__(self): return _SpatialFilter.SpatialFilterPtr___invert__(self)
    def __init__(self): 
        this = _SpatialFilter.new_SpatialFilterPtr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _SpatialFilter.delete_SpatialFilterPtr
    __del__ = lambda self : None;
    def matchesPoint(self, *args): return _SpatialFilter.SpatialFilterPtr_matchesPoint(self, *args)
    def unionFilter(self, *args): return _SpatialFilter.SpatialFilterPtr_unionFilter(self, *args)
    def intersectionFilter(self, *args): return _SpatialFilter.SpatialFilterPtr_intersectionFilter(self, *args)
    def negatedFilter(self, *args): return _SpatialFilter.SpatialFilterPtr_negatedFilter(self, *args)
    def matchingX(self, *args): return _SpatialFilter.SpatialFilterPtr_matchingX(self, *args)
    def matchingY(self, *args): return _SpatialFilter.SpatialFilterPtr_matchingY(self, *args)
    def lessThanX(self, *args): return _SpatialFilter.SpatialFilterPtr_lessThanX(self, *args)
    def lessThanY(self, *args): return _SpatialFilter.SpatialFilterPtr_lessThanY(self, *args)
    def greaterThanX(self, *args): return _SpatialFilter.SpatialFilterPtr_greaterThanX(self, *args)
    def greaterThanY(self, *args): return _SpatialFilter.SpatialFilterPtr_greaterThanY(self, *args)
    def allSpace(self): return _SpatialFilter.SpatialFilterPtr_allSpace(self)
SpatialFilterPtr_swigregister = _SpatialFilter.SpatialFilterPtr_swigregister
SpatialFilterPtr_swigregister(SpatialFilterPtr)

# This file is compatible with both classic and new-style classes.


